# Travis file

language: generic

before_install:
  - if [${TRAVIS_OS_NAME} == "linux"]; then sudo apt-get update -qq; fi
  - ./install-dependencies.sh

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libblas-dev', 'liblapack-dev', 'libopenblas-dev']
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7

script:
  - make CXX=$CXX

notifications:
  email: false
